### PR TITLE
Add search functionality

### LINKED ISSUE #68: Add global search
Add search Inuit to the primary nav. Use the`wp-json` search engine to create the search results page.

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Created the search template as a search results page. Added a form to the main navigation. Added the routing for search queries.

## QA
- Pull this branch
- Run `./run`
- Go to http://0.0.0.0:8023
- Check the homepage loads
- Search something in the navigation
- Check you land on the search results page with results

Fixes https://github.com/canonical-websites/insights.ubuntu.com/issues/68

### CODE REVIEW

**Review by deadlight — APPROVED** [review]
All good

**Comment by frankiegranato** [comment]
I feel this needs a design review. The search looks a bit squished.

**Comment by spencerbygraves** [comment]
@anthonydillon have we taken the height of the search box and button from Ubuntu.com to fit into the 48px header? It looks a bit squashed I think because the shadow above is more prominent on the white background.

Can we add a `$sp-x-small` gap between the button and field please.

@kwm14 I think we may need to specify a field and button in Vanilla less that 42px high for things like this.

**Comment by spencerbygraves** [comment]
The last dividing line isn't touching the bottom

image

**Comment by anthonydillon** [comment]
@spencerbygraves thanks, good points. I've fixed up the search styling. Can you let me know what you think please.

**Comment by spencerbygraves** [comment]
@anthonydillon there's still a gap running under the logo and links

image

And it appears to break below 993px

image

**Comment by anthonydillon** [comment]
@spencerbygraves sorry about that. Think I've caught everything now.

**Pull request merged**
