### PR TITLE
Add optional featured images to posts

### LINKED ISSUE #93: Investigate ways to add "preview post" functionality
No previewing of posts (in draft)

### LINKED ISSUE #255: Investigate pulling images into insights cards

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Add option to show thumbnails on posts

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8023/](http://0.0.0.0:8023/)
- Check that the ninth post on the homepage has a thumbnail and no intro text same as <https://www.ubuntu.com/resources>

## Issue / Card

[Fixes #255](https://app.zenhub.com/workspace/o/canonical-websites/insights.ubuntu.com/issues/255)

## Screenshots

ubuntu insights

### CODE REVIEW

**Comment by anthonydillon** [comment]
You have some lint issues. You can see them locally by running `./run test`

**Comment by steverydz** [comment]
Linting issues fixed

**Comment by frankiegranato** [comment]
Hi @steverydz So, how does the optional images function work? (only one post seems to have a featured image, but on www.ubuntu.com/resources many have images - maybe they were added manually?)

**Comment by steverydz** [comment]
@frankiegranato There has to be a featured image set on the post in WordPress. If there is one it will show, if not it will show the intro text

**Comment by pmahnke** [comment]
@steverydz @anthonydillon @frankiegranato don't we want that image on the post itself as well? 

http://insights.ubuntu.com-pr-264.run.demo.haus/2018/02/27/ubuntu-server-development-summary-27-february-2018

**Comment by anthonydillon** [comment]
We had a quick discussion on this and decided that, that might not always
be the case. The featured image might be tailored for promotional purposes
only. Where as, the post may just need contextual images.

That said, if the author does want the image in the post they can add it
with the adding flexibility of inserting where they like.

**Comment by pmahnke** [comment]
@anthonydillon let's talk, but I assume that is NOT how the current insights work and any posts with a featured image will now not show them... and this is the case for webinars

**Comment by steverydz** [comment]
Blocked until after the meeting on Friday

**Comment by pmahnke** [comment]
We just met with James Donner, he is happy with the changes that are here in this pull request.  Additionally we are going to look at the insights db and see if we need to make some older posts featured images available in the body.

**Pull request merged**
