### PR TITLE
Make the drop down menus white

### LINKED ISSUE #95: Drop down menus should be white
Please can we make the drop down menus white (background)? I think it will make them more visible. See screen shot.

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Set the background of the hover menu to white.

## QA
- Check out the demo and hover over the menu 
- The drop down menu background is white

## Details
Fixes https://github.com/canonical-websites/insights.ubuntu.com/issues/95

### CODE REVIEW

**Review by shivjoshi1996 — COMMENTED** [review]
Code & QA 👍

**Comment by anthonydillon** [comment]
@kwm14 would you mind making me one please? There isnt one on the asset server I can find.

**Comment by kwm14** [comment]
@anthonydillon sure thing, updated nav arrow in white:
- https://assets.ubuntu.com/v1/9fd5cbb7-nav-arrow-white.svg

**Comment by anthonydillon** [comment]
@kwm14 Cheers for the icon. But, the icon needs to have a top border as all the navigation is white too.

**Comment by kwm14** [comment]
@anthonydillon doh! I thought you added the border in code. Ok I will update, do you know what grey it needs to be?

**Comment by anthonydillon** [comment]
No prob. I believe its `#cdcdcd`

**Comment by kwm14** [comment]
@anthonydillon updated nav-arrow with top-border:
- https://assets.ubuntu.com/v1/b70e6370-nav-arrow-white.svg

**Comment by kwm14** [comment]
@anthonydillon there is a 1px gap between chevron and dropdown menu...is that fixable?

screen shot 2018-01-26 at 09 34 19

**Comment by kwm14** [comment]
Design 👍

**Pull request merged**
