### PR TITLE
Add card header style for tutorials and description to first two cards

### LINKED ISSUE #387: /blog Fix card styling - Dev
## Screenshot

screen shot 2018-07-09 at 16 40 29

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Add card header style for tutorials
- Add description to first two cards

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8023/](http://0.0.0.0:8023/)
- See that any cards in the tutorials category have a header style inline with the other cards
- See that the first two posts on page 1 only have summaries

## Issue / Card

Fixes #387

### CODE REVIEW

**Comment by anasereijo** [comment]
@steverydz looking good, thanks!
Is it possible to remove the descriptions from those 2 cards on mobile?

**Comment by steverydz** [comment]
@anasereijo Done

**Comment by anasereijo** [comment]
@steverydz  perfect 👍

**Review by Caleb-Ellis — APPROVED** [review]
Looks good!

**Pull request merged**
