### PR TITLE
Only show featured posts on page one

### LINKED ISSUE #333: Remove 'featured' content on all pages after page 1.
Remove 'featured' content on all pages after page 1. Eg. Only the landing homepage should show featured content at the top. All subsequent pages should not include featured content.

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Only show featured posts on page one

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8023/](http://0.0.0.0:8023/)
- Check that there are featured posts at the top of the page
- Click on any of the pagination links
- If you are not on page one see that there are no featured posts

## Issue / Card

Fixes #333

### CODE REVIEW

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Comment by frankiegranato** [comment]
Hi @steverydz this is great! However, seeing this has made me realise that I think we should also remove the Newsletter signup box from the subsequent pages (eg. so it only appears on the landing homepage). Can you please implement that?

**Comment by steverydz** [comment]
@frankiegranato I can but it should be a different ticket as it's going to be a bit more complicated

**Comment by steverydz** [comment]
@frankiegranato I've made a ticket for that request (#340)

**Comment by frankiegranato** [comment]
Sensible. Thank you @steverydz

**Pull request merged**
