### PR TITLE
Add GDPR copy to post newsletter form

### LINKED ISSUE #308: 'Subscribe now' button is broken and is positioned outside the sign up card
## Summary

Currently the 'Subscribe now' button is broken and is positioned outside the sign up card.
## Process

Issue can be found here: https://insights.ubuntu.com/2018/04/16/botsandus-build-a-social-robot-on-ubuntu

## Expected result

Buttons should be positioned inside the sign up card.

## Screenshot
screen shot 2018-04-17 at 11 16 02

### LINKED ISSUE #378: /blog - newsletter sign up is missing GDPR Copy
First reported here: https://github.com/ubuntudesign/web-squad/issues/625#issuecomment-398130998

homepage card (how it should be):

article card (missing copy):

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Add GDPR copy to newsletter form on blog post page
- Made form an include so is the same across both pages 
- Fix button style conflict 

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8023/](http://0.0.0.0:8023/)
- Go to a blog post and make sure the newsletter form is the same as the one on the homepage
- Go to <http://0.0.0.0:8023/2018/04/16/botsandus-build-a-social-robot-on-ubuntu> and make sure the newsletter form button looks correct

## Issue / Card

Fixes #378 
Fixes #308

### CODE REVIEW

**Review by Caleb-Ellis — CHANGES_REQUESTED** [review]
On http://0.0.0.0:8023/2018/04/16/botsandus-build-a-social-robot-on-ubuntu, on the sticky form, if you click the label for "Work email" or "I agree to receive...", it focuses on the one in the blog post.

**Comment by steverydz** [comment]
@Caleb-Ellis Fixed

**Comment by Caleb-Ellis** [comment]
Still getting the bug on the "Work email" input. It might be a good idea just to wrap all the inputs in a label.

**Comment by steverydz** [comment]
@Caleb-Ellis Wrapped all inputs in labels - necessary but I feel dirty

**Review by Caleb-Ellis — APPROVED** [review]
LGTM :+1:

@steverydz Really? I always thought that was the better way to write form inputs, because you get to drop the `id` and `for` attributes  :confused:

**Comment by steverydz** [comment]
@Caleb-Ellis I thinks it's great for radios and checkboxes but for text inputs I don't really like it. I guess technically there's nothing wrong with it though.

**Pull request merged**
