### PR TITLE
Update the footer

### LINKED ISSUE #504: Update the footer legal terms
footer wording to be amended from "Privacy policy" to Data privacy"

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Updated the year, legal link names
- Updated to the vanilla footer pattern
- Added the canonical logo

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8023/](http://0.0.0.0:8023/)
- See that the 'footer wording to be amended from "Privacy policy" to Data privacy"'

## Issue / Card

Fixes #504

### CODE REVIEW

**Comment by anasereijo** [comment]
I don't think we have the canonical logo in any other websites. Was this requested? If so, I think it needs a bit of design work.

**Comment by pmahnke** [comment]
I can remove it, but I think Mark was talking about adding it everywhere

**Review by steverydz — APPROVED** [review]
LGTM :+1:

**Comment by anasereijo** [comment]
@pmahnke looking good 👍 
If the canonical logo needs to be added everywhere I think we should create an epic for that. Probably that will be a Vanilla squad task?

**Pull request merged**
