### PR TITLE
Build new featured posts module

### LINKED ISSUE #313: Insights hompage changes - build

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Build new featured posts section

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8023/](http://0.0.0.0:8023/)
- Check that the featured posts section matches the proposed design

## Issue / Card

Fixes #313

### CODE REVIEW

**Comment by steverydz** [comment]
@anasereijo @spencerbygraves The demo show's the heading as a h5 and this screenshot as a h6

screenshot from 2018-05-04 12-03-41

**Comment by anasereijo** [comment]
@steverydz I think h5 looks better, thanks

**Comment by spencerbygraves** [comment]
@steverydz @anasereijo yes, I prefer h5. Thanks for updating it.

**Comment by anasereijo** [comment]
@steverydz looks great!

**Comment by anasereijo** [comment]
@frankiegranato what do you think about having the 3 featured posts on mobile? The way it is now is to scroll down until we see the other cards but I was wondering if we can 1) have just 1 featured post on mobile or 2) have a horizontal scroll to see them?

**Comment by steverydz** [comment]
@anasereijo @frankiegranato I'd be in favour of keeping all three on mobile. The only way to only show one at a different screen size is to hide the others, which means the user still has to pay the tax of that markup being on the page and downloading any images etc.

In general my opinion is if the content isn't important enough for one screen size, should it be there on any screen size?

**Comment by anasereijo** [comment]
@steverydz you're right, we should have them on mobile too.

But if the users want to filter the content once they land on the page they need to scroll down and I was wondering if it's too much to scroll on smaller devices? If it is maybe we can have a horizontal scroller for featured posts like this example: https://flowmapp.com/blog/ (see mobile version).

Or maybe this is not necessary as I am not sure from a UX perspective how much users are willing to scroll down... @frankiegranato any thoughts?

**Review by Caleb-Ellis — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
